repos:
  - repo: local
    hooks:
      - id: flake8
        name: Flake8 Linter
        entry: flake8
        language: system
        types: [python]
        args: ["--config=.flake8"]

      - id: black
        name: Black Formatter
        entry: black
        language: system
        types: [python]
        args: ["--config=pyproject.toml"]

      - id: isort
        name: Isort Import Sorter
        entry: isort
        language: system
        types: [python]
        args: ["--settings=pyproject.toml"]
