[tool.black]
line-length = 79  
target-version = ['py312']

exclude = '''
/(
    \.git
  | __pycache__
  | venv
)/
'''

[tool.isort]
profile = "black" 
line_length = 79  
skip = [".git", "__pycache__", "venv"]



