name: Lint FastAPI Code

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Code Quality Estandar with Flake8
        run: flake8 .

      - name: check de Formato de codigo
        run: black --check .

      - name: Check de orden de imports
        run: isort . --check-only
